#分组名和服务名可以随便取，只要保持同组配置里，分组名一致即可

#端口转发配置
[Forward.分组名]
type  = 1是本地转发，2是远程转发
addr  = "服务器ip:port"
user  = "ssh帐号"
auth  = "ssh密码、私钥文件或私钥文本"
phrase= "私钥的密码"
skipKeep  = true/false
[Forward.分组名.inner.服务名]
addr  = "内网机器ip:port"
bind  = "本地绑定端口"
[Forward.分组名.indirect.分组名]
addr  = "服务器ip:port"
user  = "ssh帐号"
auth  = "ssh密码、私钥文件或私钥文本"
phrase= "私钥的密码"
skipKeep  = true/false
[Forward.分组名.indirect.分组名.inner.服务名]
addr  = "内网机器ip:port"
bind  = "本地绑定端口"

#代理配置
[proxy.分组名]
addr  = "服务器ip:port"
user  = "ssh帐号"
auth  = "ssh密码、私钥文件或私钥文本"
phrase= "私钥的密码"
timeout = 5
skipKeep  = true/false
[proxy.分组名.inner.服务名]
bind    = "本地绑定端口"
is_http = 是否http代理，true(http/https) or false(socks5)
is_ssh  = 是否指定走ssh，true or false
is_pac  = 是否根据pac走ssh，true or false
is_break= 如果不符合pac，是否中止, true or false
[proxy.分组名.domainpac]
deny=["不许访问的域名1","不许访问的域名2"]
allow=["允许访问的域名3","允许访问的域名4"]
